In [1]:
# Parameters, to be overwritten by papermill when run as nextflow pipeline
project_id = "1"
opt_run_id = "1"
token = "1e9549ad7e940941de51ddff92b1dc9cbe896e98b039644b9eff165e0dec9e55"
base_url = "https://mhs.ngrok.app/"

In [2]:
# Parameters
project_id = "181"
opt_run_id = "218"
token = "1e9549ad7e940941de51ddff92b1dc9cbe896e98b039644b9eff165e0dec9e55"
base_url = "https://mhs.ngrok.app/"


In [3]:
# Packages
import sys
print(sys.path)
import json

import numpy as np
import pandas as pd

['/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/work/55/15add8fe2e9ae1f7faeaf30f351d2d', '/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/conda_env/MSFlow-BoTorch-44b6c04a7707e21b815078bc79a67588/lib/python310.zip', '/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/conda_env/MSFlow-BoTorch-44b6c04a7707e21b815078bc79a67588/lib/python3.10', '/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/conda_env/MSFlow-BoTorch-44b6c04a7707e21b815078bc79a67588/lib/python3.10/lib-dynload', '', '/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/conda_env/MSFlow-BoTorch-44b6c04a7707e21b815078bc79a67588/lib/python3.10/site-packages']


In [4]:
# 1. Initialise API client
import MHSapi
from MHSapi.MHSapi import MHSapiClient
from importlib.metadata import version

client = MHSapi.MHSapi.MHSapiClient(token=token, base_url=base_url)
print(version('MHSapi'))
print(MHSapi.__file__)
print(dir(MHSapi))
object_methods = [method_name for method_name in dir(client)
                  if callable(getattr(client, method_name))]
print(object_methods)

projects = client.experiments_list()
project = [p for p in projects if int(p.id) == int(project_id)][0]
parameters = client.parameters_list(project)


BASE URL: https://mhs.ngrok.app/


0.0.2
/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/conda_env/MSFlow-BoTorch-44b6c04a7707e21b815078bc79a67588/lib/python3.10/site-packages/MHSapi/__init__.py
['MHSapi', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
['__class__', '__delattr__', '__dir__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'experiment_data', 'experiment_update_data', 'experiments_create', 'experiments_list', 'get_base_url', 'open_experiment', 'opt_run_list', 'parameters_create', 'parameters_list']


{}
[Experiment(id=181, url='http://localhost:8000/experiments/181/', name_text='Photonite-2024', data_table_json=''), Experiment(id=180, url='http://localhost:8000/experiments/180/', name_text='Photonite-2024', data_table_json=''), Experiment(id=179, url='http://localhost:8000/experiments/179/', name_text='Photonite-2024', data_table_json=''), Experiment(id=178, url='http://localhost:8000/experiments/178/', name_text='Photonite-2024', data_table_json=''), Experiment(id=177, url='http://localhost:8000/experiments/177/', name_text='Photonite-2024', data_table_json=''), Experiment(id=176, url='http://localhost:8000/experiments/176/', name_text='Photonite-2024', data_table_json=''), Experiment(id=170, url='http://localhost:8000/experiments/170/', name_text='Photonite-2023', data_table_json=''), Experiment(id=162, url='http://localhost:8000/experiments/162/', name_text='SyngasFermentationSim', data_table_json=''), Experiment(id=161, url='http://localhost:8000/experiments/161/', name_text='P

In [5]:
# 2. Download dataset
dataset = client.experiment_data(project)
print("Data")
print(dataset)

{"import_timestamp":{"0":1704909395.6911211014,"1":1704909395.6911211014,"2":1704909395.6911211014,"3":1704909395.6911211014,"4":1704909395.6911211014,"5":1704909395.6911211014,"6":1704909395.6911211014,"7":1704909395.6911211014,"8":1704909395.6911211014},"disabled":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":0.0,"5":0.0,"6":0.0,"7":0.0,"8":0.0},"Temperature (Celsius)":{"0":10.5,"1":12.3,"2":11.7,"3":25.5,"4":28.0,"5":15.0,"6":13.5,"7":25.0,"8":26.8},"Biomass Yield (g\/m3)":{"0":910.6302258842,"1":955.2308874596,"2":934.0850461644,"3":977.3216897534,"4":918.4279047088,"5":962.6146346605,"6":959.1759260206,"7":979.7014651398,"8":946.5538356882}}
Data
   import_timestamp  disabled  Temperature (Celsius)  Biomass Yield (g/m3)
0      1.704909e+09         0                   10.5            910.630226
1      1.704909e+09         0                   12.3            955.230887
2      1.704909e+09         0                   11.7            934.085046
3      1.704909e+09         0                   2

In [6]:
# 3. Get OptApp options

opt_runs = client.opt_run_list(project)
print(opt_runs)
opt_run = [p for p in opt_runs if int(p.id) == int(opt_run_id)][0]
print(opt_run)
#type = type(opt_run.run_options)
#method_list = [func for func in dir(type) if callable(getattr(type, func))]
#print(method_list)
import json
run_options = json.loads(opt_run.run_options.json())

batch_size = 1
if 'batch_size' in run_options.keys():
    batch_size = run_options['batch_size']

[OptimisationRun(id=215, experiment=181, opt_app=None, run_options=Xc2ef1593_308e_4caf_ac27_e5db48363025(root={})), OptimisationRun(id=216, experiment=181, opt_app=3, run_options=Xc2ef1593_308e_4caf_ac27_e5db48363025(root={'batch_size': 1})), OptimisationRun(id=217, experiment=181, opt_app=3, run_options=Xc2ef1593_308e_4caf_ac27_e5db48363025(root={'batch_size': 3})), OptimisationRun(id=218, experiment=181, opt_app=3, run_options=Xc2ef1593_308e_4caf_ac27_e5db48363025(root={'batch_size': 1}))]
id=218 experiment=181 opt_app=3 run_options=Xc2ef1593_308e_4caf_ac27_e5db48363025(root={'batch_size': 1})


/tmp/ipykernel_97615/4232612496.py:11: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  run_options = json.loads(opt_run.run_options.json())


In [7]:





# 4. Do BO
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

from botorch.models.transforms.input import Normalize
from botorch.models.transforms.outcome import Standardize

inputs = [p for p in parameters if p.outcome == False and p.timestamp == False]
outcome = [p for p in parameters if p.outcome == True][0]
X = dataset[[i.parameter_text for i in inputs]]
Y = dataset[[outcome.parameter_text]]
train_X = torch.tensor(X.to_numpy(dtype=np.float64))
train_Y = torch.tensor(Y.to_numpy(dtype=np.float64))
#train_Y = standardize(train_Y)
print(train_X.shape)
print(train_X)
print(train_Y.shape)
print(train_Y)

gp = SingleTaskGP(train_X, train_Y, input_transform=Normalize(d=train_X.shape[-1]), outcome_transform=Standardize(m=train_Y.shape[-1]))

mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_mll(mll)

#from botorch.acquisition import UpperConfidenceBound
#UCB = UpperConfidenceBound(gp, beta=0.1)

from botorch.optim import optimize_acqf

from botorch import fit_gpytorch_mll
from botorch.acquisition.monte_carlo import (
    qExpectedImprovement,
    qNoisyExpectedImprovement,
)
from botorch.sampling.normal import SobolQMCNormalSampler
from botorch.exceptions import BadInitialCandidatesWarning

upper_bounds = torch.tensor([p.upper_bound for p in inputs])
lower_bounds = torch.tensor([p.lower_bound for p in inputs])
bounds = torch.stack([lower_bounds, upper_bounds])
print(f"batch_size={batch_size}")

SMOKE_TEST = False
MC_SAMPLES = 256 if not SMOKE_TEST else 32
qmc_sampler = SobolQMCNormalSampler(sample_shape=torch.Size([MC_SAMPLES]))

qNEI = qNoisyExpectedImprovement(
    model=gp,
    X_baseline=train_X,
    sampler=qmc_sampler,
)
candidates, acq_value = optimize_acqf(
    acq_function=qNEI, bounds=bounds, q=int(batch_size), num_restarts=5, raw_samples=20,
)
candidates  # tensor([0.4887, 0.5063])
print("Candidates (raw):")
print(candidates.detach())

candidates = pd.DataFrame(candidates.numpy())
candidates.columns = [input.parameter_text for input in inputs]
candidates[outcome.parameter_text] = np.nan
candidates["opt_run_id"] = opt_run_id

print(candidates)


/Users/jakobzeitler/MatterhornStudioLocalDev/BoTorchGeneralOptApp/conda_env/MSFlow-BoTorch-44b6c04a7707e21b815078bc79a67588/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.Size([9, 1])
tensor([[10.5000],
        [12.3000],
        [11.7000],
        [25.5000],
        [28.0000],
        [15.0000],
        [13.5000],
        [25.0000],
        [26.8000]], dtype=torch.float64)
torch.Size([9, 1])
tensor([[910.6302],
        [955.2309],
        [934.0850],
        [977.3217],
        [918.4279],
        [962.6146],
        [959.1759],
        [979.7015],
        [946.5538]], dtype=torch.float64)
batch_size=1.0
Candidates (raw):
tensor([[21.9115]])
   Temperature (Celsius)  Biomass Yield (g/m3) opt_run_id
0              21.911505                   NaN        218


In [8]:
# 5. Upload candidates
client.experiment_update_data(project, candidates)
